# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('taxonomy_custom.json', '.'),
    ],
    hiddenimports=[
        'drive_organizer',
        'drive_organizer.auth.google_auth',
        'drive_organizer.drive.client',
        'drive_organizer.drive.models',
        'drive_organizer.ai.base',
        'drive_organizer.ai.privacy',
        'drive_organizer.ai.cache',
        'drive_organizer.ai.cascade',
        'drive_organizer.ai.ollama_provider',
        'drive_organizer.ai.haiku_provider',
        'drive_organizer.ai.opus_provider',
        'drive_organizer.strategies.base',
        'drive_organizer.strategies.by_type',
        'drive_organizer.strategies.by_date',
        'drive_organizer.strategies.by_project',
        'drive_organizer.strategies.custom',
        'drive_organizer.planner',
        'drive_organizer.executor',
        'drive_organizer.rollback',
        'drive_organizer.wizard',
        'drive_organizer.renamer',
        'drive_organizer.rename_executor',
        'drive_organizer.duplicate_finder',
        'drive_organizer.content_extractor',
        'drive_organizer.ui.tree_diff',
        'drive_organizer.ui.prompts',
        'drive_organizer.ui.console',
        'drive_organizer.ui.rename_diff',
        'drive_organizer.ui.duplicate_diff',
        'drive_organizer.config',
        'google.auth',
        'google.auth.transport.requests',
        'google.oauth2.credentials',
        'google_auth_oauthlib.flow',
        'googleapiclient.discovery',
        'googleapiclient.errors',
        'googleapiclient.http',
        'drive_organizer.ai.gemini_provider',
        'anthropic',
        'google.genai',
        'google.genai.types',
        'pydantic',
        'pydantic_settings',
        'rich',
        'click',
        'requests',
        'web',
        'flask',
        'werkzeug',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['credentials.json'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='drive-organizer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
